### ISSUE TITLE
你好，这个内存泄漏怎么解决；

### ISSUE THREAD

**Issue by 13018585117** [MattLjp/LinphoneCall#1]
![1683511497170](https://user-images.githubusercontent.com/42494041/236720557-ef23d583-23e4-4793-83ab-44659f670f8e.png)

**Comment by MattLjp** [comment]
这是你代码造成的内存泄漏，仔细检查自己的代码

**Comment by 13018585117** [comment]
我

> 这是你代码生成的内部漏洞，仔仔细检查自己的代码

LinphoneManager全局单例，  设置core.nativeVideoWindowId = videoRendering
        core.nativePreviewWindowId = videoPreview，
activity关闭，再把这个两个设置为null,一样不起作用
